kickreason: Scheduled shutdown.
warntimes: 900,600,300,240,180,120,60,45,30,20,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1
gracetime: 20
kickonshutdown: true
shutdowntimes: 3:00,8:00,11:00,14:00,17:00,2:13
shutdownnow: Server is shutting down NOW!
shutdownXseconds: Server is shutting down in %d seconds ...
shutdown1minute: Server is shutting down in 1 minute ...
shutdown1minuteXseconds: Server is shutting down in 1 minute %d seconds ...
shutdownXminutes: Server is shutting down in %d minutes ...
shutdownXminutesXseconds: Server is shutting down in %d minutes %d seconds ...